MovieProject/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IMDBCore;
//ing System.Web.Script.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore;
using MovieProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace MovieProject.Controllers

{
    public class MoviesController : Controller
    {
        private readonly MovieProjectContext _context;
        private readonly IConfiguration _configuration;

        //ivate readonly JavaScriptSerializer _jsonSerializer;

        public MoviesController(MovieProjectContext context, IConfiguration Configuration)
        {
            //this._jsonSerializer = new JavaScriptSerializer();
            _context = context;
            _configuration = Configuration;
        }

        public List<Movie> GetMoviesByGenre(string p_genre)
        {
            var movies = this._context.Movie.Where(x => x.Genre == p_genre).ToList();
            return movies;
        }

        public List<Movie> GetMoviesByDirector(string p_director)
        {
            var movies = this._context.Movie.Where(x => x.Director == p_director).ToList();
            return movies;
        }
        public List<Movie> GetMoviesByReleaseYear(int p_releaseYear)
        {
            var movies = this._context.Movie.Where(x => x.ReleaseDate.Year == p_releaseYear).ToList();
            return movies;
        }
        // GET: Movies
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Movie.Include(x=>x.MovieSupplier).ToListAsync());
        }
        public IActionResult Search(string title = null, int? year = null, string genere = null, string director = null,int? priceFrom=null,int? priceTo=null,int? SupplierId = null)
        {
            PopulateSuppliersDropDownList();
            return View(this.GetMoviesBySearchParams(title, year, genere, director,priceFrom,priceTo, SupplierId));
        }
        public List<Movie> GetMoviesBySearchParams(string p_movieTitle = null, int? p_releaseYear = null, string p_genere = null, string p_director = null ,int? p_priceFrom=null, int? p_priceTo = null,int? p_supplierId=null)
        {
            var queryOver = this._context.Movie.AsQueryable();

            if (!string.IsNullOrEmpty(p_movieTitle))
            {
                queryOver = queryOver.Where(x => x.Title == (p_movieTitle));
            }
            if (p_releaseYear.HasValue)
            {
                queryOver = queryOver.Where(x => x.ReleaseDate.Year == p_releaseYear.Value);
            }
            if (!string.IsNullOrEmpty(p_genere))
            {
                queryOver = queryOver.Where(x => x.Genre == p_genere);
            }
            if (!string.IsNullOrEmpty(p_director))
            {
                queryOver = queryOver.Where(x => x.Director == p_director);
            }
            if (p_priceFrom.HasValue)
            {
                queryOver = queryOver.Where(x => x.Price >= p_priceFrom);
            }
            if (p_priceTo.HasValue)
            {
                queryOver = queryOver.Where(x => x.Price <= p_priceTo);
            }
            if (p_supplierId.HasValue)
            {
                // join query with suppliers              
                queryOver = queryOver.Join(this._context.Supplier,
                     m => m.SupplierId,
                     s => s.ID,
                 (m, s) => new Movie { ID = m.ID, Title = m.Title, ReleaseDate = m.ReleaseDate, Genre = m.Genre, Price = m.Price, Director = m.Director, Length = m.Length, MinimalAge = m.MinimalAge, MovieSupplier = s })
                .Where(x=>x.MovieSupplier.ID == p_supplierId.Value);

                //queryOver = queryOver.Where(x => x.MovieSupplier.ID == p_supplierId.Value);
               
            }
            var result = queryOver.Select(x => new Movie { ID=x.ID, Title = x.Title, ReleaseDate = x.ReleaseDate, Genre = x.Genre, Price = x.Price,Director =x.Director, Length=x.Length,MinimalAge=x.MinimalAge,MovieSupplier = x.MovieSupplier }).ToList();

            // return this._jsonSerializer.Serialize(result); // Run the query and avoid context dispose
            return result;

        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);

            if (movie == null)
            {
                return NotFound();
            }

            ImdbMovie movieRev= this.GetMovieData(movie.Title);
    

            return View("details",movieRev);
        }

        // GET: Movies/Create
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public IActionResult Create()
        {
            PopulateSuppliersDropDownList();
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create([Bind("ID,Title,ReleaseDate,Genre,Price,Director,Length,MinimalAge,SupplierId")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthorId = new SelectList(_context.Supplier, "ID", "Name", movie.SupplierId);
            //PopulateSuppliersDropDownList(movie.SupplierId);
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }
            PopulateSuppliersDropDownList(movie.MovieSupplier.ID);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,ReleaseDate,Genre,Price,Director,Length,MinimalAge")] Movie movie)
        {
            if (id != movie.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            PopulateSuppliersDropDownList(movie.MovieSupplier.ID);
            return View(movie);
        }


        // GET: Movies/Delete/5
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Microsoft.AspNetCore.Authorization.Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ImdbMovie GetMovieData(string movieName)
        {
            string  API_KEY =  _configuration.GetSection("AppSettings")["ImdbApiKey"];

            var imdb = new Imdb(API_KEY);
            var movie =  imdb.GetMovieAsync(movieName);

           return movie.Result;

            
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.ID == id);
        }
        private void PopulateSuppliersDropDownList(object selectedSupplier = null)
        {
            var suppliersQuery = from d in _context.Supplier
                                   orderby d.Name
                                   select d;
            
            ViewBag.SupplierId = new SelectList(suppliersQuery, "ID", "Name", selectedSupplier);
            //new SelectList()
        }
    }
}

MovieProject/Controllers/RecommenderController.cs
using System.Collections.Generic;
using System.Linq;

using System.IO;




using NReco.CF.Taste.Model;
using NReco.CF.Taste.Impl.Model.File;
using NReco.CF.Taste.Impl.Eval;
using NReco.CF.Taste.Eval;
using NReco.CF.Taste.Impl.Similarity;
using NReco.CF.Taste.Impl.Neighborhood;
using NReco.CF.Taste.Impl.Recommender;
using NReco.CF.Taste.Impl.Recommender.SVD;
using NReco.CF.Taste.Impl.Model;
using NReco.CF.Taste.Recommender;

using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Caching.Memory;

namespace Controllers
{

    public class RecommenderController : Controller
    {

        private IHostingEnvironment _env;
        private IMemoryCache _cache;

        public RecommenderController(IHostingEnvironment env, IMemoryCache cache)
        {
            _env = env;
            _cache = cache;
        }

        public ActionResult Index()
        {
            return View();
        }

        static IDataModel dataModel;

        public ActionResult GetRecommendedFilms(string filmIdsJson)
        {
            var filmIds = JsonConvert.DeserializeObject<long[]>(filmIdsJson);

            var dataModel = GetDataModel();

            // recommendation is performed for the user that is missed in the preferences data
            var plusAnonymModel = new PlusAnonymousUserDataModel(dataModel);
            var prefArr = new GenericUserPreferenceArray(filmIds.Length);
            prefArr.SetUserID(0, PlusAnonymousUserDataModel.TEMP_USER_ID);
            for (int i = 0; i < filmIds.Length; i++)
            {
                prefArr.SetItemID(i, filmIds[i]);

                // in this example we have no ratings of movies preferred by the user
                prefArr.SetValue(i, 5); // lets assume max rating
            }
            plusAnonymModel.SetTempPrefs(prefArr);

            var similarity = new LogLikelihoodSimilarity(plusAnonymModel);
            var neighborhood = new NearestNUserNeighborhood(15, similarity, plusAnonymModel);
            var recommender = new GenericUserBasedRecommender(plusAnonymModel, neighborhood, similarity);
            var recommendedItems = recommender.Recommend(PlusAnonymousUserDataModel.TEMP_USER_ID, 5, null);

            return Json(recommendedItems.Select(ri => new Dictionary<string, object>() {
                {"film_id", ri.GetItemID() },
                {"rating", ri.GetValue() },
            }).ToArray());
        }

        /// <summary>
        /// Loads data model (preferences data) from the file. In the same manner data can be loaded from SQL database (or MongoDb).
        /// </summary>
        /// <remarks>
        /// Data model is cached to avoid CSV parsing on each request.
        /// </remarks>
        IDataModel GetDataModel()
        {

            var webRoot = _env.WebRootPath;
            var file = System.IO.Path.Combine(webRoot, "ratings.csv");

            var cacheKey = "RecommenderDataModel:" + file;

            var dataModel = _cache.Get(cacheKey) as IDataModel;
            if (dataModel == null)
            {
                dataModel = new FileDataModel(file, false, FileDataModel.DEFAULT_MIN_RELOAD_INTERVAL_MS, false);
                _cache.Set(cacheKey, dataModel);
            }
            return dataModel;
        }

        public ActionResult GetMovies()
        {

            var webRoot = _env.WebRootPath;
            var file = System.IO.Path.Combine(webRoot, "movies.csv");

            var csv = new CsvReader(new StreamReader(file));
            var records = csv.GetRecords<MovieRecord>();
            return Json(records);
        }

        public class MovieRecord
        {
            public int movieId { get; set; }
            public string title { get; set; }
        }

    }
}

MovieProject/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MovieProject.Controllers
{
    public class StatisticController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movie Store</title>

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    
    <link rel="stylesheet" href="~/css/animate.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)

</head>
<body>


    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><img width="30px" style="display:inline-block" id="app-logo" src="~/images/viewster-logo-300x300.png" />Movie App</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="StoreBranches" asp-action="MapView">Branches</a></li>
					<li><a asp-area="" asp-controller="Movies" asp-action="Search">Movies</a></li>
					<li><a asp-area="" asp-controller="customers" asp-action="Search">Customer</a></li>
					<li><a asp-area="" asp-controller="Recommender" asp-action="index">Movie Recommender</a></li>
					<li><a asp-area="" asp-controller="Statistic" asp-action="index">Statistics</a></li>

                    @if (User.IsInRole("Admin"))
                    {
                           <li><a asp-area="" asp-controller="suppliers" asp-action="Search">Suppliers</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MovieProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script>

    @*<script src="~/js/typehead.js"></script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>